-- Gastenhuis Keukenhulp — complete menukaarten / kaartenbak
-- Uitvoeren in de Supabase SQL editor.
-- Deze tabel staat bewust los van week_menus: week_menus is planning/historie,
-- menu_cards is de herbruikbare kaartenbak.

create table if not exists public.menu_cards (
  id bigint generated by default as identity primary key,
  title text not null,
  menu_type text not null default 'regular' check (menu_type in ('regular','veggie')),
  lactose_free boolean not null default false,
  seasons text[] not null default '{}',

  main_id text,
  starch_id text,
  vegetable_id text,
  salad_id text,
  sauce_id text,
  stamppot_id text,
  dessert_id text,

  favorite boolean not null default false,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint menu_cards_seasons_valid check (
    seasons <@ array['spring','summer','autumn','winter']::text[]
  )
);

-- Exact dezelfde kaart mag maar één keer voorkomen.
-- COALESCE voorkomt dat NULL-velden duplicaten doorlaten.
create unique index if not exists menu_cards_unique_combination
on public.menu_cards (
  menu_type,
  lactose_free,
  coalesce(main_id,''),
  coalesce(starch_id,''),
  coalesce(vegetable_id,''),
  coalesce(salad_id,''),
  coalesce(sauce_id,''),
  coalesce(stamppot_id,''),
  coalesce(dessert_id,'')
);

create index if not exists menu_cards_active_idx
on public.menu_cards (archived, menu_type, lactose_free);

create index if not exists menu_cards_seasons_idx
on public.menu_cards using gin (seasons);

-- updated_at automatisch bijwerken
create or replace function public.set_menu_cards_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_menu_cards_updated_at on public.menu_cards;
create trigger trg_menu_cards_updated_at
before update on public.menu_cards
for each row execute function public.set_menu_cards_updated_at();

-- De huidige keukenapp gebruikt de publishable/anon key zonder login.
-- Daarom dezelfde praktische toegangsopzet als de bestaande centrale appdata.
alter table public.menu_cards enable row level security;

drop policy if exists "menu_cards_read" on public.menu_cards;
create policy "menu_cards_read"
on public.menu_cards for select
to anon, authenticated
using (true);

drop policy if exists "menu_cards_insert" on public.menu_cards;
create policy "menu_cards_insert"
on public.menu_cards for insert
to anon, authenticated
with check (true);

drop policy if exists "menu_cards_update" on public.menu_cards;
create policy "menu_cards_update"
on public.menu_cards for update
to anon, authenticated
using (true)
with check (true);

-- Bewust géén delete-policy: kaarten archiveren we in plaats van definitief verwijderen.
